### PR TITLE
add the hash algorithm named sm3.

### PR DESCRIPTION
**Pull request by DongyunLee**
[There](https://tools.ietf.org/id/draft-oscca-cfrg-sm3-02.html#:~:text=SM3%20Cryptanalysis%20Comparison%20%20%20%20Algorithm%20,%20%20%5BKEKKAC-ZSD%5D%20%2022%20more%20rows%20) is some introduce about *SM3 Cryptographic Hash Algorithm*.

It's become more popular in China, and have been added to *openssl*.

so i think maybe we can add it to our amazing tools~

### CODE REVIEW

**Comment by DongyunLee** [comment]
I'm in China, so when i use the Taobao Mirror of Npm packages,  *yarn.lock* records it.

I think it maybe should be modified for other countries' developer, but i don't know how to change it🤔.
Maybe it should be change for The Official Mirror of Npm packages? I don't know……

So, review it please😁

**Comment by rb-x** [comment]
Hello @DongyunLee Thank you for the suggestion,I will implement it soon :)
What do you think @LasCC  ?

**Comment by DongyunLee** [comment]
👀

**Comment by LasCC** [comment]
> 👀

Hi there! Apologies for the delayed response, I'm currently working on the next version of the extension.

I will add your hash algorithm on the next version 👍

Thanks for the request!

**Pull request closed without merging**
